#!/usr/bin/env bash
# This script displays all active IPv4 IP addresses on the current machine

ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1
ip -4 -o addr show scope host | awk '{print $4}' | cut -d/ -f1
